name: patient_app
description: "AyuSync Patient Premium Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_fonts: ^8.2.1
  http: ^1.6.0
  lucide_icons: ^0.257.0
  dio: ^5.4.3
  flutter_riverpod: ^2.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  min_sdk_android: 21