"""Add chat, appointments, tasks, geolocation

Revision ID: 46b716e825e4
Revises: 8a8136c28c06
Create Date: 2026-08-30 10:09:01.886845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '46b716e825e4'
down_revision: Union[str, Sequence[str], None] = '8a8136c28c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('participant_1_id', sa.String(), nullable=False),
    sa.Column('participant_2_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('practitioner_id', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('assigned_role', postgresql.ENUM('PATIENT', 'CAREGIVER', 'NURSE', 'DOCTOR', 'PHARMACIST', 'LAB_TECH', 'INSURANCE_REP', 'AMBULANCE_DRIVER', 'ADMIN', name='userrole', create_type=False), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('due_time', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ambulance_drivers', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('ambulance_drivers', sa.Column('current_lng', sa.Float(), nullable=True))
    op.add_column('emergency_dispatches', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('emergency_dispatches', sa.Column('pickup_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_dispatches', 'pickup_lng')
    op.drop_column('emergency_dispatches', 'pickup_lat')
    op.drop_column('ambulance_drivers', 'current_lng')
    op.drop_column('ambulance_drivers', 'current_lat')
    op.drop_table('chat_messages')
    op.drop_table('care_tasks')
    op.drop_table('appointments')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
