"""Initial 9-stakeholder schema

Revision ID: 8a8136c28c06
Revises: 
Create Date: 2026-08-28 10:45:41.640146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8136c28c06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_type', sa.Enum('PHARMACY', 'LABORATORY', 'INSURANCE', 'HOSPITAL', name='orgtype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('agent_source', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'CAREGIVER', 'NURSE', 'DOCTOR', 'PHARMACIST', 'LAB_TECH', 'INSURANCE_REP', 'AMBULANCE_DRIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('ambulance_drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vehicle_license_plate', sa.String(), nullable=True),
    sa.Column('is_on_duty', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('caregiver_id', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practitioners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('npi_number', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi_number')
    )
    op.create_table('care_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('protocol_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_escalations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('shap_explanation', sa.Text(), nullable=False),
    sa.Column('doctor_decision', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_dispatches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('pickup_location', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EN_ROUTE', 'ARRIVED', 'DELIVERED', name='dispatchstatus'), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['ambulance_drivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('lab_id', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('prescribed_by_id', sa.String(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prior_authorizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('insurance_org_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_queues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('assigned_nurse_id', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='triageseverity'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_nurse_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adherence_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('medication_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('TAKEN', 'MISSED', 'SYSTEMIC_DELAY', name='adherencestatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lab_order_id', sa.String(), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('medication_id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_proactive_10_day', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacy_orders')
    op.drop_table('lab_results')
    op.drop_table('adherence_logs')
    op.drop_table('vitals')
    op.drop_table('triage_queues')
    op.drop_table('prior_authorizations')
    op.drop_table('medications')
    op.drop_table('lab_orders')
    op.drop_table('encounters')
    op.drop_table('emergency_dispatches')
    op.drop_table('doctor_escalations')
    op.drop_table('care_plans')
    op.drop_table('practitioners')
    op.drop_table('patients')
    op.drop_table('hospital_admins')
    op.drop_table('ambulance_drivers')
    op.drop_table('users')
    op.drop_table('system_audit_logs')
    op.drop_table('organizations')
    # ### end Alembic commands ###
